repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        files: ^(aiogram|tests)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        files: ^(aiogram|tests)
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3 # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910' # pick sha/tag from https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        files: aiogram
